import 'package:get/get.dart';

class TranslatedString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'hello': 'Hello - En',
      'splash_greetings': 'Xin chào bạn!',
      'splash_updating': 'đang cập nhật dữ liệu mới. Xin vui lòng chờ...',
      'user_name_title': 'Tên đăng nhập',
      'password_title': 'Mật khẩu',
      'email_error_text': 'Email không đúng địng dạng',
      'invalid_format_error_text': 'Không đúng địng dạng',
      'password_error_text': 'Mật khẩu phải có ít nhất 6 ký tự',
      'login_text': 'Đăng nhập',
      'logout_text': 'Đăng xuất',
      'error_title': 'Lỗi',
      'ok_title': 'OK',
      'request_cancel_text': 'Huỷ',
      'notification_text': 'Thông báo',
      'request_text': 'Yêu cầu',
      'no_internet': 'Không có kết nối',
      'profile_text': 'Tài khoản',
      'profile_info_text': 'Thông tin cá nhân',
      'edit_profile_text': 'Chỉnh sửa thông tin',
      'full_name_text': 'Họ và tên',
      'gender_text': 'Giới tính',
      'email_text': 'Email',
      'phone_number_text': 'Số điện thoại',
      'address_text': 'Địa chỉ',
      'location_text': 'Địa điểm',
      'birthday_text': 'Ngày sinh',
      'save_text': 'Lưu',
      'done_text': 'Xong',
      'input_required_error_text': 'Bắt buộc nhập',
      'male_text': 'Nam',
      'female_text': 'Nữ',
      'choose_from_camera_text': 'Chụp ảnh',
      'choose_from_gallery_text': 'Thư viện',
      'unread_notification_text': 'Thông báo chưa đọc',
      'at_text': 'lúc',
      'request_management_text': 'Quản lý yêu cầu',
      'request_new_title': 'Yêu cầu mới',
      'request_in_progress_title': 'Yêu cầu đang xử lý',
      'request_done_title': 'Yêu cầu xử lý thành công',
      'request_failed_title': 'Yêu cầu xử lý thất bại',
      'request_cancel_title': 'Yêu cầu huỷ',
      'request_details_text': 'Chi tiết yêu cầu',
      'name_search_text': 'Tìm tên',
      'reset_filter_text': 'Thiết lập lại',
      'customer_name_text': 'Tên khách hàng',
      'customer_name__short_text': 'Tên KH',
      'request_in_progress_text': 'Đang xử lý',
      'request_done_text': 'Xử lý thành công',
      'request_failed_text': 'Xử lý thất bại',
      'filter_title_text': 'Lọc theo trường',
      'time_text': 'Thời gian',
      'from_text': 'Từ',
      'to_text': 'Đến',
      'card_value_text': 'Hạn mức (triệu)',
      'card_value_normal_text': 'Hạn mức',
      'age_range_text': 'Độ tuổi',
      'confirm_text': 'Xác nhận',
      'exit_text': 'Thoát',
      'meeting_time_text': 'Thời gian hẹn gặp',
      'meeting_location_text': 'Địa điểm hẹn gặp',
      'meeting_discuss_content_text': 'Nội dung trao đổi',
      'meeting_result_content_text': 'Kết quả hẹn',
      'request_content_text': 'Nội dung yêu cầu',
      'logout_confirm_text': 'Bạn chắc chắn muốn đăng xuất khỏi thiết bị này?',
      'general_error_text': 'Không thể kết nối với server, vui lòng thử lại sau!',
      'session_expired_error_text': 'Phiên đăng nhập hết hạn, vui lòng đăng nhập lại!',
      'pass_request_text': 'Bỏ qua',
      'data_not_valid_text': 'Không hợp lệ',
      'request_filter_date': 'Thời gian',
      'request_filter_card_value': 'Giá trị',
      'request_filter_gender': 'Giới tính',
      'request_filter_age': 'Tuổi',
      'exit_warning': 'Nhấn lần nữa để thoát',
      'statistic_text': 'Thống kê',
      'request_code_text': 'Mã yêu cầu',
      'employee_text': 'Nhân viên',
      'open_account_consulting_text': 'Tư vấn mở thẻ',
      'request_time_text': 'Thời gian gửi',
      'personal_id_text': 'CMND/CCCD',
      'request_sale_name_text': 'Nhân viên tiếp nhận',
      'request_status_text': 'Trạng thái yêu cầu',
      'book_meeting_success_text': 'Cập nhật lịch hẹn',
      'book_meeting_confirm_text': 'Bạn có chắc chắn đã đặt hẹn thành công?',
      'finalize_text': 'Hoàn tất',
      'meeting_result_text': 'Kết quả cuộc hẹn',
      'request_cancel_reason_text': 'Lý do hủy',
      'customer_rating_text': 'Đánh giá của Khách hàng',
      'skip_request_text': 'Bỏ qua yêu cầu',
      'new_request_text': 'Yêu cầu mới',
      'request_information_changed_text': 'Thay đổi thông tin',
      'see_more_text': 'Xem thêm',
      'cancel_request_text': 'Huỷ yêu cầu',
      'request_report_title_text': 'Báo cáo kết quả',
      'meet_customer_success_text': 'Đã gặp khách hàng',
      'meet_customer_failure_text': 'Không gặp được Khách hàng',
      'image_video_text': 'Hình ảnh, video',
      'confirm_request_complete_text': 'Xác nhận hoàn thành',
      'select_file_type_text': 'Chọn loại tệp',
      'video_text': 'Video',
      'image_text': 'Hình ảnh',
      'upload_file_from_text': 'Chọn từ',
      'camera_text': 'Camera',
      'device_text': 'Thiết bị',
      'statistic_time_type_text': 'Theo thời gian',
      'statistic_status_type_text': 'Theo trạng thái',
      'statistic_rating_type_text': 'Theo đánh giá của khách hàng',
      'customer_info_title_text': 'Thông tin của khách hàng',
      'day_text': 'Ngày',
      'month_text': 'Tháng',
      'year_text': 'Năm',
      'one_star_text': '1 sao',
      'two_star_text': '2 sao',
      'three_star_text': '3 sao',
      'four_star_text': '4 sao',
      'five_star_text': '5 sao',
      'no_data_text': 'Không tìm thấy dữ liệu',
      'update_request_appointment_text': 'Cập nhật lịch hẹn',
      'product_text': 'Sản phẩm',
      'note_text': 'Ghi chú',
      'assigned_sale_info_text': 'Thông tin sales tiếp nhận',
      'go_to_settings_text': 'Cài đặt',
      'turn_on_gps_text': 'Bật GPS ',
      'sale_code_text': 'Mã sale ',
      'newest_text': 'Mới nhất',
      'oldest_text': 'Cũ nhất',
      'request_time_left_text': 'Thời gian xử lý còn lại',
      'mark_read_all_text': 'Đánh dấu tất cả đã đọc',
      'view_map_text': 'Xem bản đồ',
      'rating_text': 'Xếp hạng',
      'search_text': 'Tìm kiếm',
      'maps_location_text': 'Bản đồ chỉ vị trí',
      'average_time_text': 'Thời gian xử lý trung bình',
      'total_time_text': 'Tổng thời gian xử lý',
      'contact_customer_deadline_time_text': 'Thời gian phải liên lạc KH',
      'advice_through_phone_text': 'Tư vấn qua điện thoại',
      'advice_meet_directly_text': 'Gặp trực tiếp',
      'advice_method_text': 'Hình thức tư vấn',
      'advice_result_text': 'Kết quả tư vấn',
      'hour_text': 'giờ',
      'minute_text': 'phút',
      'accept_text': 'Chấp nhận',
    },
    'vi_VN': {
      'hello': 'Xin chào',
      'splash_greetings': 'Xin chào bạn!',
      'splash_updating': 'đang cập nhật dữ liệu mới. Xin vui lòng chờ...',
      'user_name_title': 'Tên đăng nhập',
      'password_title': 'Mật khẩu',
      'email_error_text': 'Email không đúng địng dạng',
      'invalid_format_error_text': 'Không đúng địng dạng',
      'password_error_text': 'Mật khẩu phải có ít nhất 6 ký tự',
      'login_text': 'Đăng nhập',
      'logout_text': 'Đăng xuất',
      'error_title': 'Lỗi',
      'ok_title': 'OK',
      'request_cancel_text': 'Huỷ',
      'notification_text': 'Thông báo',
      'request_text': 'Yêu cầu',
      'no_internet': 'Không có kết nối',
      'profile_text': 'Tài khoản',
      'profile_info_text': 'Thông tin cá nhân',
      'edit_profile_text': 'Chỉnh sửa thông tin',
      'full_name_text': 'Họ và tên',
      'gender_text': 'Giới tính',
      'email_text': 'Email',
      'phone_number_text': 'Số điện thoại',
      'address_text': 'Địa chỉ',
      'location_text': 'Địa điểm',
      'birthday_text': 'Ngày sinh',
      'save_text': 'Lưu',
      'done_text': 'Xong',
      'input_required_error_text': 'Bắt buộc nhập',
      'male_text': 'Nam',
      'female_text': 'Nữ',
      'choose_from_camera_text': 'Chụp ảnh',
      'choose_from_gallery_text': 'Thư viện',
      'unread_notification_text': 'Thông báo chưa đọc',
      'at_text': 'lúc',
      'request_management_text': 'Quản lý yêu cầu',
      'request_new_title': 'Yêu cầu mới',
      'request_in_progress_title': 'Yêu cầu đang xử lý',
      'request_done_title': 'Yêu cầu xử lý thành công',
      'request_failed_title': 'Yêu cầu xử lý thất bại',
      'request_cancel_title': 'Yêu cầu huỷ',
      'request_details_text': 'Chi tiết yêu cầu',
      'name_search_text': 'Tìm tên',
      'reset_filter_text': 'Thiết lập lại',
      'customer_name_text': 'Tên khách hàng',
      'customer_name__short_text': 'Tên KH',
      'request_in_progress_text': 'Đang xử lý',
      'request_done_text': 'Xử lý thành công',
      'request_failed_text': 'Xử lý thất bại',
      'filter_title_text': 'Lọc theo trường',
      'time_text': 'Thời gian',
      'from_text': 'Từ',
      'to_text': 'Đến',
      'card_value_text': 'Hạn mức (triệu)',
      'card_value_normal_text': 'Hạn mức',
      'age_range_text': 'Độ tuổi',
      'confirm_text': 'Xác nhận',
      'exit_text': 'Thoát',
      'meeting_time_text': 'Thời gian hẹn gặp',
      'meeting_location_text': 'Địa điểm hẹn gặp',
      'meeting_discuss_content_text': 'Nội dung trao đổi',
      'meeting_result_content_text': 'Kết quả hẹn',
      'request_content_text': 'Nội dung yêu cầu',
      'logout_confirm_text': 'Bạn chắc chắn muốn đăng xuất khỏi thiết bị này?',
      'general_error_text': 'Không thể kết nối với server, vui lòng thử lại sau!',
      'session_expired_error_text': 'Phiên đăng nhập hết hạn, vui lòng đăng nhập lại!',
      'pass_request_text': 'Bỏ qua',
      'data_not_valid_text': 'Không hợp lệ',
      'request_filter_date': 'Thời gian',
      'request_filter_card_value': 'Giá trị',
      'request_filter_gender': 'Giới tính',
      'request_filter_age': 'Tuổi',
      'exit_warning': 'Nhấn lần nữa để thoát',
      'statistic_text': 'Thống kê',
      'request_code_text': 'Mã yêu cầu',
      'employee_text': 'Nhân viên',
      'open_account_consulting_text': 'Tư vấn mở thẻ',
      'request_time_text': 'Thời gian gửi',
      'personal_id_text': 'CMND/CCCD',
      'request_sale_name_text': 'Nhân viên tiếp nhận',
      'request_status_text': 'Trạng thái yêu cầu',
      'book_meeting_success_text': 'Cập nhật lịch hẹn',
      'book_meeting_confirm_text': 'Bạn có chắc chắn đã đặt hẹn thành công?',
      'finalize_text': 'Hoàn tất',
      'meeting_result_text': 'Kết quả cuộc hẹn',
      'request_cancel_reason_text': 'Lý do hủy',
      'customer_rating_text': 'Đánh giá của Khách hàng',
      'skip_request_text': 'Bỏ qua yêu cầu',
      'new_request_text': 'Yêu cầu mới',
      'request_information_changed_text': 'Thay đổi thông tin',
      'see_more_text': 'Xem thêm',
      'cancel_request_text': 'Huỷ yêu cầu',
      'request_report_title_text': 'Báo cáo kết quả',
      'meet_customer_success_text': 'Đã gặp khách hàng',
      'meet_customer_failure_text': 'Không gặp được Khách hàng',
      'image_video_text': 'Hình ảnh, video',
      'confirm_request_complete_text': 'Xác nhận hoàn thành',
      'select_file_type_text': 'Chọn loại tệp',
      'video_text': 'Video',
      'image_text': 'Hình ảnh',
      'upload_file_from_text': 'Chọn từ',
      'camera_text': 'Camera',
      'device_text': 'Thiết bị',
      'statistic_time_type_text': 'Theo thời gian',
      'statistic_status_type_text': 'Theo trạng thái',
      'statistic_rating_type_text': 'Theo đánh giá của khách hàng',
      'customer_info_title_text': 'Thông tin của khách hàng',
      'day_text': 'Ngày',
      'month_text': 'Tháng',
      'year_text': 'Năm',
      'one_star_text': '1 sao',
      'two_star_text': '2 sao',
      'three_star_text': '3 sao',
      'four_star_text': '4 sao',
      'five_star_text': '5 sao',
      'no_data_text': 'Không tìm thấy dữ liệu',
      'update_request_appointment_text': 'Cập nhật lịch hẹn',
      'product_text': 'Sản phẩm',
      'note_text': 'Ghi chú',
      'assigned_sale_info_text': 'Thông tin sales tiếp nhận',
      'go_to_settings_text': 'Cài đặt',
      'turn_on_gps_text': 'Bật GPS ',
      'sale_code_text': 'Mã sale ',
      'newest_text': 'Mới nhất',
      'oldest_text': 'Cũ nhất',
      'request_time_left_text': 'Thời gian xử lý còn lại',
      'mark_read_all_text': 'Đánh dấu tất cả đã đọc',
      'view_map_text': 'Xem bản đồ',
      'rating_text': 'Xếp hạng',
      'search_text': 'Tìm kiếm',
      'maps_location_text': 'Bản đồ chỉ vị trí',
      'average_time_text': 'Thời gian xử lý trung bình',
      'total_time_text': 'Tổng thời gian xử lý',
      'contact_customer_deadline_time_text': 'Thời gian phải liên lạc KH',
      'advice_through_phone_text': 'Tư vấn qua điện thoại',
      'advice_meet_directly_text': 'Gặp trực tiếp',
      'advice_method_text': 'Hình thức tư vấn',
      'advice_result_text': 'Kết quả tư vấn',
      'hour_text': 'giờ',
      'minute_text': 'phút',
      'accept_text': 'Chấp nhận',
    }
  };

}